#!/usr/bin/env python3
"""unverified-report — the standing "what still needs a source" worklist.

Hand-maintained verification checklists in tickets (fsspx#1 §1 and friends) go
stale the moment someone edits a dataset. The datasets already carry the truth:
`dateVerified: false`, `verified: false`, and prose marked "(to verify)" /
"to confirm" / "unverified". This walks every project dataset and prints that
worklist, grouped by repo and collection, with the entity and the exact flagged
field — so the checklist is regenerated, never remembered.

`--markdown` emits a paste-ready checklist for a ticket comment.

Agent-side analysis tooling: Python 3 stdlib only, never runs in CI, READ-ONLY.
It reports what the data says; it never clears a flag and never edits a file.
Clearing a flag is a sourcing decision (sourcing-rules #1) and stays with the
human/agent who found the source.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

_dq = None


def dq():
    """Load dataset-query.py's helpers (one definition of the flag rule)."""
    global _dq
    if _dq is None:
        import importlib.util
        path = os.path.join(HERE, "dataset-query.py")
        spec = importlib.util.spec_from_file_location("dataset_query", path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        _dq = module
    return _dq


DEFAULT_REPOS = ("fsspx", "tariqa", "perennialism", "rcc", "glossary")


def natural_key(locator):
    """Sort 'events[9]' before 'events[24]' rather than lexically."""
    return tuple(int(part) if part.isdigit() else part
                 for part in re.split(r"(\d+)", locator))


def collect(repo_arg):
    """[(collection, locator, entity, field, reason, value)] for one repo."""
    q = dq()
    repo = q.resolve_repo(repo_arg)
    data, kind = q.load_dataset(repo)
    rows = []
    for collection, locator, rec in q.iter_records(data):
        for field, reason, value in q.flagged_fields(rec):
            rows.append({
                "collection": collection,
                "locator": locator,
                "entity": q.record_id(rec),
                "field": field or "-",
                "reason": reason,
                "value": value or "-",
            })
    rows.sort(key=lambda r: (r["collection"], natural_key(r["locator"]),
                             r["field"]))
    return {"repo": os.path.basename(repo), "kind": kind, "path": repo,
            "rows": rows}


def group_by_collection(rows):
    groups = {}
    for row in rows:
        groups.setdefault(row["collection"], []).append(row)
    return [(name, groups[name]) for name in sorted(groups)]


def render_text(reports):
    out = ["# unverified-report | repos=%d | flags=%d"
           % (len(reports), sum(len(r["rows"]) for r in reports)),
           "rule: dateVerified:false, verified:false, or text matching "
           "(to verify)/to confirm/unverified",
           "fields: locator | entity | field | reason | value"]
    for report in reports:
        out.append("")
        out.append("## %s (%s) — %d" % (report["repo"], report["kind"],
                                        len(report["rows"])))
        if report.get("error"):
            out.append("error: %s" % report["error"])
            continue
        for collection, rows in group_by_collection(report["rows"]):
            out.append("### %s (%d)" % (collection, len(rows)))
            for row in rows:
                out.append("%s | %s | %s | %s | %s"
                           % (row["locator"], row["entity"], row["field"],
                              row["reason"], row["value"]))
    return "\n".join(out)


def render_markdown(reports):
    total = sum(len(r["rows"]) for r in reports)
    out = ["## Verification worklist",
           "",
           "Generated by `core/tools/unverified-report.py` — regenerate rather "
           "than edit by hand. %d open flag(s) across %d dataset(s). A flag "
           "clears only when a source is cited (sourcing-rules #1)."
           % (total, len(reports)),
           ""]
    for report in reports:
        out.append("### %s (%d)" % (report["repo"], len(report["rows"])))
        if report.get("error"):
            out.append("- error: %s" % report["error"])
            out.append("")
            continue
        if not report["rows"]:
            out.append("- none")
            out.append("")
            continue
        for collection, rows in group_by_collection(report["rows"]):
            out.append("")
            out.append("**%s**" % collection)
            for row in rows:
                detail = "" if row["value"] == "-" else " — %s" % row["value"]
                out.append("- [ ] `%s` %s — `%s` (%s)%s"
                           % (row["locator"], row["entity"], row["field"],
                              row["reason"], detail))
        out.append("")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="unverified-report.py",
        description="List every unverified flag across project datasets "
                    "(dateVerified:false, verified:false, '(to verify)'). "
                    "Read-only.",
        epilog="Default repos: %s. Repos may be names or paths."
               % ", ".join(DEFAULT_REPOS))
    ap.add_argument("repos", nargs="*", help="repo names or paths")
    ap.add_argument("--markdown", action="store_true",
                    help="emit a paste-ready ticket checklist")
    ap.add_argument("--json", action="store_true", help="JSON output")
    args = ap.parse_args(argv)

    targets = args.repos or list(DEFAULT_REPOS)
    reports, failed = [], 0
    for target in targets:
        try:
            reports.append(collect(target))
        except (IOError, OSError, ValueError) as exc:
            failed += 1
            reports.append({"repo": os.path.basename(str(target)),
                            "kind": "-", "path": str(target), "rows": [],
                            "error": str(exc)})
    if args.json:
        print(json.dumps({"repos": reports,
                          "total": sum(len(r["rows"]) for r in reports)},
                         ensure_ascii=False, indent=1))
    elif args.markdown:
        print(render_markdown(reports))
    else:
        print(render_text(reports))
    return 1 if failed and failed == len(targets) else 0


if __name__ == "__main__":
    sys.exit(main())
